error-check.sh: Allow `YDB_TARGET_COMMIT` to be in an unmerged branch
Previously, it only worked for commits that had already been merged for the master branch.

Additionally, I removed some dead code for the case where there is already a local clone; that's already handled by the commands
below.

I tested locally that this makes `error-check.sh` work for the still-open JSON MR:
```
$ YDB_TARGET_COMMIT=d6405d625ace7c87a068cd6e8802c60ffe24a9f0 ci/error-check.sh
Updating git checkout of git-checkouts/YDB
'upstream/HEAD' is unchanged and points to 'master'
Preparing worktree (detached HEAD d6405d625)
HEAD is now at d6405d625 [#474] Simplify dlsym() calls for various function pointers
From gitlab.com:YottaDB/DB/YDB
 * branch                d6405d625ace7c87a068cd6e8802c60ffe24a9f0 -> FETCH_HEAD
HEAD is now at d6405d625 [#474] Simplify dlsym() calls for various function pointers
Checking MessageRecovery/errors.rst is in sync with git-checkouts/YDB/sr_port/*.msg

ERROR: JANSSONINVALIDJSON was documented in git-checkouts/YDB/sr_port/ydberrors.msg:86 but not in MessageRecovery/errors.rst
ERROR: JANSSONENCODEERROR was documented in git-checkouts/YDB/sr_port/ydberrors.msg:87 but not in MessageRecovery/errors.rst
ERROR: JANSSONDLERROR was documented in git-checkouts/YDB/sr_port/ydberrors.msg:85 but not in MessageRecovery/errors.rst
NOTE: none of the failures were automatically fixable. You will have to fix the errors manually.
Failed: 3/1524

Checking MessageRecovery/errormsgref.rst is in sync with git-checkouts/YDB/sr_port/*.msg

ERROR: JANSSONINVALIDJSON was documented in git-checkouts/YDB/sr_port/ydberrors.msg:86 but not in MessageRecovery/errormsgref.rst
ERROR: JANSSONENCODEERROR was documented in git-checkouts/YDB/sr_port/ydberrors.msg:87 but not in MessageRecovery/errormsgref.rst
ERROR: JANSSONDLERROR was documented in git-checkouts/YDB/sr_port/ydberrors.msg:85 but not in MessageRecovery/errormsgref.rst
NOTE: none of the failures were automatically fixable. You will have to fix the errors manually.
Failed: 3/1511
```