Give a better error for undocumented errors
There is some overlap in the checks that are being done. Both error_sync.py and the bash code on line 39 are checking that there is a 1-1 correspondence between errors in sr_port/ydb*errors.h and errormsgref.rst. But they have different error handling, and error_sync.py gives more details about where the mismatch happened. Since error-check.sh exits on the first error, running error_sync.py first means that error-check.sh gives a better overall error when this mismatch happens.

Previously:
```
FATAL: message number recorded in errormsgref.rst is NOT accurate
Please check diff output below:
1554d1553
< 151028146 STACKRANGE
```

After this change:
```
Checking MessageRecovery/errors.rst is in sync with git-checkouts/YDB/sr_port/*.msg

ERROR: STACKRANGE was documented in git-checkouts/YDB/sr_port/ydberrors.msg:82 but not in MessageRecovery/errors.rst
NOTE: none of the failures were automatically fixable. You will have to fix the errors manually.
Failed: 1/1512

Checking MessageRecovery/errormsgref.rst is in sync with git-checkouts/YDB/sr_port/*.msg

ERROR: STACKRANGE was documented in git-checkouts/YDB/sr_port/ydberrors.msg:82 but not in MessageRecovery/errors.rst
NOTE: none of the failures were automatically fixable. You will have to fix the errors manually.
Failed: 1/1501
```