[#430] Fix ci/target-branch.sh and ci/error-check.sh to stop on error in pages pipeline job
Background
----------
* The `pages` pipeline job failed at https://gitlab.com/ksbhaskar/YDBDoc/-/jobs/8999479273.

Issue
-----
* The `pages` job output at the above url was misleading (pasted below).

  ```
  $ make test
  .
  .
  HEAD is now at 6b685317 [r2.02] Prepare for YottaDB r2.02 release
  .
  .
  fixed 3/15 errors and generated corrected file at /tmp/errors-2n2czay5.rst
  NOTE: 12 errors could not be fixed automatically and need to be fixed manually.
  .
  .
  Failed: 15/1504
  make: *** [Makefile:52: test] Error 1
  ```

* The final summary line said `Failed: 15/1504` which made me think that there were 15 messages
  which are incorrectly documented in this MR.

* But looking at the `HEAD is now` message pasted above, the job clearly compared the
  YDBDoc MR documentation changes in the MR (which was based off the `r2.04` branch) against
  the `r2.02` version of YDB. And that is where the problem is.

* The MR was based off the `r2.04` branch but not off the LATEST `r2.04` branch. And because of
  this, the `ci/target-branch.sh ydb` script invocation in `ci/error-check.sh` actually issued
  an error but that got hidden and execution continued afterwards resulting in the misleading
  error messages.

* See https://gitlab.com/YottaDB/DB/YDBDoc/-/merge_requests/822#note_2324102152 for more details.

Fix
---
* A `set -e` is added to the following scripts to ensure an error stops processing right there
  instead of continuing and producing misleading output.
  - ci/error-check.sh
  - ci/target-branch.sh

* In addition, `ci/error-check.sh` invoked `ci/target-branch.sh` using the following fancy syntax.

  ```sh
  : ${YDB_TARGET_COMMIT:=$(ci/target-branch.sh ydb)}
  ```

  This is a concise way of saying that if `YDB_TARGET_COMMIT` env var is not defined, set it
  to the result of the `ci/target-branch.sh ydb` invocation.

  But the disadvantage of this approach is that the `set -e` is not inherited by the subshell
  invocation and so an error inside `ci/target-branch.sh ydb` does not terminate the
  `ci/error-check.sh` invocation.

  The issue might be aggravated by the use of `/bin/sh` in the shebang line instead of `/bin/bash`.
  I did not investigate if it is easy to change sh to bash since an easy alternative is to avoid
  the `:=` syntax and instead explicitly check for whether the variable is unset (or set to `""`)
  and if so set it to the result of the `ci/target-branch.sh ydb` invocation in the same shell
  (and avoid a subshell invocation).

* With the changes in the above 2 bullets, the same job gave the following much more usable output
  (pasted below from https://gitlab.com/nars1/YDBDoc/-/jobs/9002186917).

  ```
  .
  .
  ci/error-check.sh
  From https://gitlab.com/YottaDB/DB/YDBDoc
   * [new tag]         d1.28      -> d1.28
   * [new tag]         d2.00      -> d2.00
  ERROR: HEAD should be based off [r2.04] or [master] branch.
  ERROR: This script will not work correctly until the situation is fixed.
  make: *** [Makefile:52: test] Error 1
  ```

  Notice the `ERROR:` lines at the end of the output which clearly show the problem.