[#435] Remove GVREPLERR error documentation (nixed in YDB@20fbfe6f)
Background
----------
* @dlwicksell reported the `pages` pipeline job failing in the `r2.04` branch.

* The below failure is from https://gitlab.com/dlwicksell/YDBDoc/-/jobs/10454474775

  ```
  Checking MessageRecovery/errors.rst is in sync with git-checkouts/YDB/sr_port/*.msg
  ERROR: GVREPLERR was documented in MessageRecovery/errors.rst:5503 but not in git-checkouts/YDB/sr_port/*.msg
  ```

Issue
-----
* The `GVREPLERR` error was removed in YDB@20fbfe6f. Below is pasted from that commit message.

  > As part of removing the `if` block, logic that issued a `GVREPLERR` error was also removed.
  > Therefore, also removed this error message from `sr_port/merrors.msg` and replaced it with
  > an unused message name.

* Because of that, `GVREPLERR` error should also be removed from the documentation so YDB master
  and YDBDoc r2.04 branch are in sync as far as error messages are concerned.

Fix
---
* This commit removes documentation for `GVREPLERR` in the r2.04 branch.